"""telemetry tables

Revision ID: 0001
Revises:
Create Date: 2026-09-15 20:14:53.296626
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "logs",
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("service", sa.String(length=128), nullable=False),
        sa.Column("severity_num", sa.SmallInteger(), nullable=False),
        sa.Column("severity_text", sa.String(length=16), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("trace_id", sa.String(length=32), nullable=True),
        sa.Column("span_id", sa.String(length=16), nullable=True),
        sa.Column("attrs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("scenario_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_logs_scenario_service_sev",
        "logs",
        ["scenario_id", "service", "severity_num"],
        unique=False,
    )
    op.create_index("ix_logs_service_ts", "logs", ["service", "ts"], unique=False)
    op.create_index("ix_logs_trace", "logs", ["trace_id"], unique=False)
    op.create_table(
        "metric_points",
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("service", sa.String(length=128), nullable=False),
        sa.Column("metric_name", sa.String(length=256), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column("attrs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("scenario_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_metrics_service_name_ts",
        "metric_points",
        ["service", "metric_name", "ts"],
        unique=False,
    )
    op.create_table(
        "spans",
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("span_id", sa.String(length=16), nullable=False),
        sa.Column("parent_span_id", sa.String(length=16), nullable=True),
        sa.Column("service", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("start_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("status_code", sa.String(length=8), nullable=False),
        sa.Column("status_message", sa.Text(), nullable=True),
        sa.Column("attrs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("scenario_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_spans_scenario_service_status",
        "spans",
        ["scenario_id", "service", "status_code"],
        unique=False,
    )
    op.create_index("ix_spans_service_start", "spans", ["service", "start_ts"], unique=False)
    op.create_index("ix_spans_trace", "spans", ["trace_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_spans_trace", table_name="spans")
    op.drop_index("ix_spans_service_start", table_name="spans")
    op.drop_index("ix_spans_scenario_service_status", table_name="spans")
    op.drop_table("spans")
    op.drop_index("ix_metrics_service_name_ts", table_name="metric_points")
    op.drop_table("metric_points")
    op.drop_index("ix_logs_trace", table_name="logs")
    op.drop_index("ix_logs_service_ts", table_name="logs")
    op.drop_index("ix_logs_scenario_service_sev", table_name="logs")
    op.drop_table("logs")
    # ### end Alembic commands ###
