"""service_edges

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-19 18:45:15.860791
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_edges",
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("caller", sa.String(length=128), nullable=False),
        sa.Column("callee", sa.String(length=128), nullable=False),
        sa.Column("call_count", sa.Integer(), nullable=False),
        sa.Column("err_count", sa.Integer(), nullable=False),
        sa.Column("p95_ms", sa.Float(), nullable=False),
        sa.Column("scenario_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_service_edges_scenario_callee", "service_edges", ["scenario_id", "callee"], unique=False
    )
    op.create_index(
        "ix_service_edges_window_caller", "service_edges", ["window_start", "caller"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_service_edges_window_caller", table_name="service_edges")
    op.drop_index("ix_service_edges_scenario_callee", table_name="service_edges")
    op.drop_table("service_edges")
    # ### end Alembic commands ###
