"""incidents_change_events_alert_rules

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-19 19:04:41.423776
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alert_rules",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("service", sa.String(length=128), nullable=True),
        sa.Column("metric", sa.String(length=64), nullable=False),
        sa.Column(
            "comparator",
            sa.Enum(">", ">=", "<", "<=", name="comparator", native_enum=False),
            nullable=False,
        ),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("window_s", sa.Integer(), nullable=False),
        sa.Column("for_windows", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "change_events",
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "deploy",
                "flag",
                "scale",
                "restart",
                "commit",
                name="changetype",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("service", sa.String(length=128), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("scenario_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_change_events_scenario", "change_events", ["scenario_id"], unique=False)
    op.create_index("ix_change_events_ts", "change_events", ["ts"], unique=False)
    op.create_table(
        "incidents",
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("service", sa.String(length=128), nullable=False),
        sa.Column("alert_rule_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "investigating",
                "awaiting_approval",
                "remediating",
                "resolved",
                "failed",
                name="incidentstatus",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("autonomy_level", sa.Integer(), nullable=False),
        sa.Column("scenario_id", sa.String(length=64), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["alert_rule_id"],
            ["alert_rules.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_incidents_opened_at", "incidents", ["opened_at"], unique=False)
    op.create_index("ix_incidents_status", "incidents", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_incidents_status", table_name="incidents")
    op.drop_index("ix_incidents_opened_at", table_name="incidents")
    op.drop_table("incidents")
    op.drop_index("ix_change_events_ts", table_name="change_events")
    op.drop_index("ix_change_events_scenario", table_name="change_events")
    op.drop_table("change_events")
    op.drop_table("alert_rules")
    # ### end Alembic commands ###
